# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions
# More info on Python, GitHub Actions, and Azure App Service: https://aka.ms/python-webapps-actions

name: Build and deploy Python app to Azure Web App - babymaker-app-1750608342

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python version
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Create and start virtual environment
        run: |
          python -m venv venv
          source venv/bin/activate
          echo "$VIRTUAL_ENV/bin" >> $GITHUB_PATH
      
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
        
      # Optional: Add step to run tests here (PyTest, Django test suites, etc.)

      - name: Prepare deployment package
        run: |
          # Create a clean deployment directory
          mkdir -p deployment
          # Copy application files (exclude unnecessary files)
          cp -r . deployment/
          cd deployment
          # Remove unnecessary files and directories
          rm -rf .git .github venv __pycache__ .pytest_cache .env.example
          find . -name "*.pyc" -delete
          find . -name "__pycache__" -type d -exec rm -rf {} + 2>/dev/null || true

      - name: Upload artifact for deployment jobs
        uses: actions/upload-artifact@v4
        with:
          name: python-app
          path: deployment/
          retention-days: 1

  deploy:
    runs-on: ubuntu-latest
    needs: build
    permissions:
      id-token: write
      contents: read
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: python-app
          path: ./app

      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_27EB45EB66014B498CA4293D93293CF2 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_C440761579D34C649159500030E60580 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_93DC882E935E473DB24A24ACCD31CF0B }}

      - name: 'Deploy to Azure Web App'
        uses: azure/webapps-deploy@v3
        id: deploy-to-webapp
        with:
          app-name: 'babymaker-app-1750608342'
          slot-name: 'Production'
          package: './app'
          startup-command: 'python -m streamlit run app.py --server.port 8000 --server.address 0.0.0.0'
        
      - name: Verify deployment
        run: |
          echo "Deployment completed. Waiting for app to start..."
          sleep 30
          curl -f https://babymaker-app-1750608342.azurewebsites.net/ || echo "App may still be starting up"
          